Upstream AnyKernel3 to latest

diff --git a/AnyKernel3/META-INF/com/google/android/update-binary b/AnyKernel3/META-INF/com/google/android/update-binary
--- a/AnyKernel3/META-INF/com/google/android/update-binary
+++ b/AnyKernel3/META-INF/com/google/android/update-binary
@@ -18,6 +18,11 @@ ui_print() {
     shift;
   done;
 }
+ui_printfile() {
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < $1;
+}
 show_progress() { echo "progress $1 $2" > $OUTFD; }
 file_getprop() { $bb grep "^$2=" "$1" | $bb cut -d= -f2-; }
 int2ver() {
@@ -30,7 +35,7 @@ int2ver() {
   fi;
 }
 cleanup() {
-  cd $home/..;
+  cd $(dirname $home);
   rm -rf $home;
 }
 debugging() {
@@ -42,23 +47,29 @@ debugging() {
     ;;
   esac;
 }
-is_mounted() { $bb mount | $bb grep " $1 "; }
-unmount_all() {
+setup_mountpoint() {
+  if [ -L $1 -o ! -d $1 ]; then
+    rm -f $1;
+    mkdir $1;
+  fi;
+}
+is_mounted() { $bb mount | $bb grep -q " $1 "; }
+umount_all() {
   ($bb umount /system;
-  if [ -d /system_root -a ! -f /system/build.prop ]; then
+  if [ -e /system_root ] && [ ! -f /system/build.prop -o -L /system ]; then
     $bb umount /system_root;
   fi;
   $bb umount /system;
-  $bb umount /vendor;
+  umount /vendor;
   $bb umount /data) 2>/dev/null;
 }
 abort() {
-  ui_print "$*";
+  ui_print "$@";
   debugging;
   if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
-  unmount_all;
+  umount_all;
   exit 1;
 }
 
@@ -71,6 +82,17 @@ unzip -o "$ZIPFILE";
 if [ $? != 0 -o ! "$(ls tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
+for arch32 in x86 arm; do
+  if [ -d $home/tools/$arch32 ]; then
+    bb=$home/tools/$arch32/busybox;
+    chmod 755 $bb;
+    $bb >/dev/null 2>&1;
+    if [ $? == 0 ]; then
+      $bb mv -f $home/tools/$arch32/* $home/tools;
+      break;
+    fi;
+  fi;
+done;
 bb=$home/tools/busybox;
 chmod 755 $bb;
 $bb chmod -R 755 tools bin;
@@ -80,33 +102,33 @@ if [ $? != 0 -o -z "$(ls bin)" ]; then
 fi;
 
 if [ -f banner ]; then
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < banner;
+  ui_printfile banner;
   ui_print " " " ";
 fi;
 
 ui_print "$(file_getprop anykernel.sh kernel.string)";
 if [ -f version ]; then
   ui_print " ";
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < version;
+  ui_printfile version;
   ui_print " ";
 fi;
 ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
 
-unmount_all;
-if [ ! "$(is_mounted /system)" ]; then
+umount_all;
+setup_mountpoint /system;
+if ! is_mounted /system; then
   $bb mount -o ro -t auto /system;
 fi;
 ($bb mount -o ro -t auto /vendor;
 $bb mount /data) 2>/dev/null;
 if [ -f /system/system/build.prop ]; then
-  $bb umount /system;
-  ($bb umount /system;
-  mkdir /system_root) 2>/dev/null;
-  $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
+  setup_mountpoint /system_root;
+  $bb mount --move /system /system_root;
+  if [ $? != 0 ]; then
+    $bb umount /system;
+    $bb umount /system 2>/dev/null;
+    $bb mount -o ro -t auto /system_root 2>/dev/null || $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
+  fi;
   $bb mount -o bind /system_root/system /system;
 fi;
 savedpath="$LD_LIBRARY_PATH";
@@ -128,34 +150,34 @@ fi;
 
 if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
   ui_print "Checking device...";
-  device="$(getprop ro.product.device)";
-  product="$(getprop ro.build.product)";
+  device=$(getprop ro.product.device);
+  product=$(getprop ro.build.product);
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
-      ui_print "$testname";
+      ui_print "$testname" " ";
       match=1;
       break;
     fi;
   done;
-  ui_print " ";
   if [ ! "$match" ]; then
-    abort "Unsupported device. Aborting...";
+    abort " " "Unsupported device. Aborting...";
   fi;
 fi;
 
-supported_ver="$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]')";
+supported_ver=$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]');
 if [ "$supported_ver" ]; then
   ui_print "Checking Android version...";
-  android_ver="$(file_getprop /system/build.prop ro.build.version.release)";
-  if [ "$(echo $supported_ver | $bb grep -)" ]; then
-    lo_ver=$(echo $supported_ver | $bb cut -d- -f1);
-    hi_ver=$(echo $supported_ver | $bb cut -d- -f2);
-    if [ "$(echo -e "$(int2ver $hi_ver)\n$(int2ver $lo_ver)\n$(int2ver $android_ver)" | $bb sort -g | $bb grep -n "$(int2ver $android_ver)" | $bb grep '^2:')" ]; then
+  android_ver=$(file_getprop /system/build.prop ro.build.version.release);
+  parsed_ver=$(int2ver $android_ver);
+  if echo $supported_ver | $bb grep -q '-'; then
+    lo_ver=$(int2ver "$(echo $supported_ver | $bb cut -d- -f1)");
+    hi_ver=$(int2ver "$(echo $supported_ver | $bb cut -d- -f2)");
+    if echo -e "$hi_ver\n$lo_ver\n$parsed_ver" | $bb sort -g | $bb grep -n "$parsed_ver" | $bb grep -q '^2:'; then
       supported=1;
     fi;
   else
     for ver in $(echo $supported_ver | $bb sed 's;,; ;g'); do
-      if [ "$(int2ver $ver)" == "$(int2ver $android_ver)" ]; then
+      if [ "$(int2ver $ver)" == "$parsed_ver" ]; then
         supported=1;
         break;
       fi;
@@ -164,8 +186,29 @@ if [ "$supported_ver" ]; then
   if [ "$supported" ]; then
     ui_print "$android_ver" " ";
   else
-    ui_print " ";
-    abort "Unsupported Android version. Aborting...";
+    abort " " "Unsupported Android version. Aborting...";
+  fi;
+fi;
+
+supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $bb grep -oE '[0-9]{4}-[0-9]{2}|-');
+if [ "$supported_lvl" ]; then
+  ui_print "Checking Android security patch level...";
+  android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
+  parsed_lvl=$(echo $android_lvl | $bb grep -oE '[0-9]{4}-[0-9]{2}');
+  if echo $supported_lvl | $bb grep -q '^\-'; then
+    lo_lvl=0000-00;
+    hi_lvl=$(echo $supported_lvl | $bb awk '{ print $2 }');
+  elif echo $supported_lvl | $bb grep -q ' - '; then
+    lo_lvl=$(echo $supported_lvl | $bb awk '{ print $1 }');
+    hi_lvl=$(echo $supported_lvl | $bb awk '{ print $3 }');
+  elif echo $supported_lvl | $bb grep -q '\-$'; then
+    lo_lvl=$(echo $supported_lvl | $bb awk '{ print $1 }');
+    hi_lvl=9999-99;
+  fi;
+  if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $bb sort -g | $bb grep -n "$parsed_lvl" | $bb grep -q '^2:'; then
+    ui_print "$android_lvl" " ";
+  else
+    abort " " "Unsupported Android security patch level. Aborting...";
   fi;
 fi;
 
@@ -190,7 +233,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
         *) modcon=system;;
       esac;
     fi;
-    if [ "$(is_mounted $modtarget)" ]; then
+    if is_mounted $modtarget; then
       $bb mount -o rw,remount -t auto $modtarget;
     fi;
     mkdir -p $(dirname $modtarget);
@@ -200,7 +243,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
     if [ "$modcon" ]; then
       chcon "u:object_r:${modcon}_file:s0" $modtarget;
     fi;
-    if [ "$(is_mounted $modtarget)" ]; then
+    if is_mounted $modtarget; then
       $bb mount -o ro,remount -t auto $modtarget;
     fi;
   done;
@@ -218,6 +261,6 @@ fi;
 test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
 test "$savedpre" && export LD_PRELOAD="$savedpre";
 
-unmount_all;
+umount_all;
 
 ui_print " " " " "Done!";
